### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by AAChartModel** [maltsugar/RollingNotice-Swift#1]
README 文档中的`labe`应改为 `label`😊

**Comment by maltsugar** [comment]
好吧 吓死了，还以为说的是英文文档呢， 那个是谷歌翻译copy的😅

**Comment by AAChartModel** [comment]
你是先写的英文文档,然后再谷歌翻译成中文文档?这么偷懒的嘛!!!???

**Comment by maltsugar** [comment]
不是啊 第一版的中文文档，直接翻译，小幅度修改。 后面就不管英文的了
