### ISSUE TITLE
当使用Navigation的时候，从第二个页面pop回来时崩溃

### ISSUE THREAD

**Issue by CodeOcenS** [maltsugar/RollingNotice-Swift#2]
具体报错位置：
  fileprivate func layoutCurrentCellAndWillShowCell() {
        let count = (self.dataSource?.numberOfRowsFor(roolingView: self))! // 这里报错，dataSource为nil
        
        if (currentIndex > count - 1) {
            currentIndex = 0
        }

**Comment by maltsugar** [comment]
感谢提出，代码确实不合理，现在已经更新，避免强制拆包。
你看情况如果该view的父VC根本不会释放，比如tab的根视图，那就没必要 停止滚动，也可以解决
