### ISSUE TITLE
数量返回为0的情况下，依然会要数据

### ISSUE THREAD

**Issue by csc-EricWu** [maltsugar/RollingNotice-Swift#4]
func numberOfRowsFor(roolingView: GYRollingNoticeView) -> Int

返回为0的情况下，依然会走
func rollingNoticeView(roolingView: GYRollingNoticeView, cellAtIndex index: Int) -> GYNoticeViewCell

**Comment by csc-EricWu** [comment]
layoutCurrentCellAndWillShowCell方法改一下
        guard let count = (self.dataSource?.numberOfRowsFor(roolingView: self),count>0) else { return }

**Comment by csc-EricWu** [comment]
layoutCurrentCellAndWillShowCell方法改一下
guard let count = self.dataSource?.numberOfRowsFor(roolingView: self) , count > 0 else { return }

**Comment by maltsugar** [comment]
1.0.8已修复，感谢建议
